
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|lpm_mult:Mult1|mult_06t:auto_generated|mac_out2                                       DSPOUT_X13_Y18_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|lpm_mult:Mult1|mult_06t:auto_generated|mac_mult1                                      DSPMULT_X13_Y18_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|lpm_mult:Mult0|mult_06t:auto_generated|mac_out2                                       DSPOUT_X13_Y19_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|lpm_mult:Mult0|mult_06t:auto_generated|mac_mult1                                      DSPMULT_X13_Y19_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|result[0]        DSPOUT_X13_Y21_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|mac_mult1        DSPMULT_X13_Y21_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|result[0]        DSPOUT_X13_Y20_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:mix2_0|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|mac_mult1        DSPMULT_X13_Y20_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_out6                                                   DSPOUT_X42_Y16_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_mult5                                                  DSPMULT_X42_Y16_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_out8                                                   DSPOUT_X42_Y17_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_mult7                                                  DSPMULT_X42_Y17_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_out4                                                   DSPOUT_X42_Y18_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_mult3                                                  DSPMULT_X42_Y18_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|w507w[0]                                                   DSPOUT_X42_Y19_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|lpm_mult:Mult0|mult_pgt:auto_generated|mac_mult1                                                  DSPMULT_X42_Y19_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|lpm_mult:Mult0|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y12_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|lpm_mult:Mult0|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y12_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|lpm_mult:Mult1|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y22_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|lpm_mult:Mult1|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y22_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|lpm_mult:Mult1|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y11_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|lpm_mult:Mult1|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y11_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|lpm_mult:Mult1|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y16_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|lpm_mult:Mult1|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y16_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|lpm_mult:Mult1|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y7_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|lpm_mult:Mult1|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y7_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|lpm_mult:Mult0|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y23_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|lpm_mult:Mult0|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y23_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|lpm_mult:Mult0|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y15_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|lpm_mult:Mult0|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y15_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|lpm_mult:Mult0|mult_06t:auto_generated|mac_out2                                DSPOUT_X13_Y8_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|lpm_mult:Mult0|mult_06t:auto_generated|mac_mult1                               DSPMULT_X13_Y8_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y9_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y9_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y25_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y25_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y10_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX8_9.mix2_8|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y10_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y14_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y14_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y3_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|nco2:nco2_i|sincos:sincos_i|lpm_mult:cosmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y3_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y24_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX1_3.mix2_2|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y24_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y17_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX6_7.mix2_6|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y17_N0
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|result[0] DSPOUT_X13_Y4_N2
set_location_assignment -to hermeslite_core:hermeslite_core_i|radio:radio_i|mix2:MIX4_5.mix2_4|nco2:nco2_i|sincos:sincos_i|lpm_mult:sinmult|mult_51t:auto_generated|mac_mult1 DSPMULT_X13_Y4_N0
