set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_envpa
set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_envop
set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_envbias
set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_clk3p3
set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_clk1p2
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rst_n
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_mdio
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_mdc
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_clk125
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx_en
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx_clk
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_tx
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx_clk
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx_dv
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to phy_rx
set_instance_assignment -name IO_STANDARD "2.5 V" -to io_tp2
set_instance_assignment -name IO_STANDARD "2.5 V" -to io_cl1
set_instance_assignment -name IO_STANDARD "2.5 V" -to pwr_clkvpa
set_instance_assignment -name IO_STANDARD "2.5 V" -to pa_en